## Hypothesis
Across 30 years of observation, increases in systemic inflammation (e.g., hsCRP, Lp-PLA2) will coincide with declines in metabolic health, as reflected by elevated HOMA-IR.

### Chekpoint 1:

compute pearson's correlation of:  
- hsCRP - HOMA-IR
- Lp-PLA2 - HOMA-IR

In [10]:
# imports
import pandas as pd
import pprint

In [11]:
df = pd.read_csv("Data/LLM_Biomarkers_Wide.csv")
df.head()

,Date,% SCFA Acetate,% SCFA Butyrate,% SCFA Propionate,% SCFA Valerate,237_mg/dL,A/G ratio_None,ALT_U/L,APO A1_mg/dL,APOLIPOPROTEIN-(B100)_mg/dL,...,Uric Acid_None,VLDL Cholesterol_mg/dL,Vitamin B12_pg/mL,"Vitamin D, 25-Hydroxy_ng/mL",Vitamin E Alpha-Tocopherol_mg/L,Vitamin E Gamma-Tocopherol_mg/L,WBC-_10**3/mL,Weight_lbs,Zinc_µg/dL,pH_None
0,1993-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996-11-27,NaN,NaN,NaN,NaN,NaN,1.3,NaN,NaN,NaN,...,6.0,NaN,NaN,NaN,NaN,NaN,8.7,NaN,NaN,NaN
2,1997-05-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.3,NaN,NaN,NaN,NaN,NaN,6.3,NaN,NaN,NaN
3,1998-04-15,NaN,NaN,NaN,NaN,NaN,1.4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.4,NaN,NaN,NaN
4,1999-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,8.7,NaN,NaN,NaN

In [12]:
temp = df.dropna(how='all', axis=1)

# only retain columns with at least 100 non-NA values
temp = temp.loc[:, temp.notna().sum() >= 100]

In [13]:
pprint.pprint(df.columns.tolist())

['Date',
 '% SCFA Acetate',
 '% SCFA Butyrate',
 '% SCFA Propionate',
 '% SCFA Valerate',
 '237_mg/dL',
 'A/G ratio_None',
 'ALT_U/L',
 'APO A1_mg/dL',
 'APOLIPOPROTEIN-(B100)_mg/dL',
 'AST/ALT ratio_None',
 'AST_U/L',
 'Actinomyces neuii_None',
 'Actinomyces turicensis_None',
 'Albumin_g/dL',
 'Alkaline phosphatase_U/L',
 'Alpha Lipoic Acid_None',
 'Alpha hemolytic strep_None',
 'Anion Gap_mmol/L',
 'Arcobacter butzieri_None',
 'BASO %',
 'BUN/Creatinine Ratio_None',
 'Bacillus cereus_None',
 'Bacillus licheniformis_None',
 'Bacillus spp, pumilus_None',
 'Bacteroides family_None',
 'Bacteroides fraglis group_None',
 'Basophil Count_10**3/mL',
 'Beta strep, group B, strep. Agalactiae_None',
 'Bicarbonate_mmol/L',
 'Bifidobacerium family_None',
 'Blood Urea Nitrogen (BUN)_mg/dL',
 'Butyrate_mg/mL',
 'CA-19-9 (Pancreatic Cancer)_U/mL',
 'CEA_ng/mL',
 'Calcium_mg/dL',
 'Candida krusei/inconspicua/lambica_None',
 'Candida lusitaniae_None',
 'Candida orthopsilosis_None',
 'Candida parapsilosis_None',
 'Candida pararugosa_None',
 'Candida zeylanoides_None',
 'Cellulosimicrobium cellulans/funkeil/marinum_None',
 'Chloride_mmol/L',
 'Chol/HDL_None',
 'Citrobacter freundii complex_None',
 'Clostridium spp_None',
 'CoQ10_None',
 'Comamonas testosteroni_None',
 'Cortisol Random_None',
 'Corynebacterium falsenii_None',
 'Creatinine_mg/dL',
 'Cryptococcus diffuens_None',
 'Cryptococcus spp, not neoformans_None',
 'DHEA-blood_µg/dL',
 'Direct Bilirubin_None',
 'E. coli spp._None',
 'EOS %',
 'Enterobacter asburiae_None',
 'Enterobacter cloacae_None',
 'Enterococcus spp._None',
 'Esoinophil Count_10**3/mL',
 'Estradiol_pg/mL',
 'Exophiala dermatitidis_None',
 'Fasting Glucose_mg/dL',
 'Ferritin_ng/mL',
 'Fibrinogen_None',
 'Free Testosterone_pg/mL',
 'GGTP_U/L',
 'Gamma Hemolytic Streptococcus_None',
 'Geotrichum spp._None',
 'Globulin_None',
 'HCT_%',
 'HDL (High Density Lipoprotein) "good"_mg/dL',
 'HGB-_g/dL',
 'HOMA-IR (insulin resistance)_None',
 'Hafnia alvei_None',
 'Hemoglobin A1C_%',
 'Hemolytic Escherichia coli_None',
 'High Sensitivity CRP (mg/L)_mg/L',
 'Homocysteine_µmol/L',
 'IDL Chloresterol_None',
 'IgA_None',
 'IgG_None',
 'IgM_None',
 'Insulin_µIU/mL',
 'Iron saturation_%',
 'Iron_µg/dL',
 'Klebsiella oxytoca_None',
 'Klebsiella pneumonia_None',
 'Kocuria spp, salsicia, rhizophila, kristinae_None',
 'LDH_U/L',
 'LYM %',
 'Lactobacillus spp_None',
 'Lactococcus lactis_None',
 'Lp(a) Chloresterol_None',
 'Lp-PLA2_None',
 'Lymphocyte Count_10**3/mL',
 'Lysinibacillus spp_None',
 'MCHC-_g/dL',
 'MCH_pg/cell',
 'MCV-_fL',
 'MONO %',
 'MPV_fL',
 'Magnesium_mg/dL',
 'Monocyte Count_10**3/mL',
 'Morganellla morganii_None',
 'Mucoid Escherichia coli_None',
 'NEU %',
 'Neutrophil Count_10**3/mL',
 'Niacin (Vit B3)_None',
 'PLT-_10**3/mL',
 'PSA Screen_None',
 'Pantoea spp_None',
 'Phosporus_mg/dL',
 'Potassium_mmol/L',
 'Providencia rettgeri_None',
 'Providencia stuartii_None',
 'Pseudomonas aeruginosa_None',
 'Pseudomonas chlororaphis group_None',
 'Pseudomonas citronellolis_None',
 'Pseudomonas stutzeri_None',
 'RBC-_10**6/mL',
 'RDW_%',
 'Ratio APO B100/AI_None',
 'Real-LDL Size Pattern_None',
 'Rhodotorula glutinis/mucilaginosa_None',
 'Rothia dentocariosa/mucliaginosa_None',
 'Saccharomyces cerevisiae/boulardi_None',
 'Selenium_None',
 'Serratia marcescens_None',
 'Sex Hormone Binding Globulin (SHBG)_nmol/L',
 'Sodium_mmol/L',
 'Staphylococcus aureus_None',
 'Staphylococcus epidermidis_None',
 'Staphylococcus haemolyticus_None',
 'Staphylococcus lugdunensis_None',
 'Stool Calprotectin UCSD_µg/g',
 'Stool Calprotectin YFH_None',
 'Stool Lactoferrin_None',
 'Stool Lysozyme_None',
 'Stool SIgA_None',
 'Streptococcus anginosus_None',
 'Streptococcus australis_None',
 'Streptococcus mitis/oralis/cristatus_None',
 'Streptococcus mutans_None',
 'Streptococcus parasanguinis_None',
 'Streptococcus salivarius_None',
 'Streptomyces_None',
 'Sum Total Cholesterol_mg/dL',
 'TG/HDL_None',
 'TIBC_µg/dL',
 'TSH_µIU/mL',
 'Testosterone % Free',
 'Thyroxine (T4)_µg/dL',
 'Tot CO2_None',
 'Total Bilirubin_mg/dL',
 'Total Protein_g/dL',
 'Total SCFA_mg/mL',
 'Total T3_ng/mL',
 'Total Testosterone_ng/mL',
 'Trichosporon asahii_None',
 'Trichosporon montevideense_None',
 'Trichosporon ovoides_None',
 'Triglycerides_mg/dL',
 'UCSD HDL Particle #_μmol/L',
 'UCSD HDL Particle Size_nm',
 'UCSD LDL Particle # by NMR_nmol/L',
 'UCSD LDL Particle Size_nm',
 'UCSD Large HDL Particle #_μmol/L',
 'UCSD Large VLDL Particle #_nmol/L',
 'UCSD Small LDL Particle #_nmol/L',
 'UCSD VLDL Particle Size_nm',
 'UIBC_µg/dL',
 'Uric Acid_None',
 'VLDL Cholesterol_mg/dL',
 'Vitamin B12_pg/mL',
 'Vitamin D, 25-Hydroxy_ng/mL',
 'Vitamin E Alpha-Tocopherol_mg/L',
 'Vitamin E Gamma-Tocopherol_mg/L',
 'WBC-_10**3/mL',
 'Weight_lbs',
 'Zinc_µg/dL',
 'pH_None']

In [14]:
pprint.pprint(df.columns.tolist())

['Date',
 '% SCFA Acetate',
 '% SCFA Butyrate',
 '% SCFA Propionate',
 '% SCFA Valerate',
 '237_mg/dL',
 'A/G ratio_None',
 'ALT_U/L',
 'APO A1_mg/dL',
 'APOLIPOPROTEIN-(B100)_mg/dL',
 'AST/ALT ratio_None',
 'AST_U/L',
 'Actinomyces neuii_None',
 'Actinomyces turicensis_None',
 'Albumin_g/dL',
 'Alkaline phosphatase_U/L',
 'Alpha Lipoic Acid_None',
 'Alpha hemolytic strep_None',
 'Anion Gap_mmol/L',
 'Arcobacter butzieri_None',
 'BASO %',
 'BUN/Creatinine Ratio_None',
 'Bacillus cereus_None',
 'Bacillus licheniformis_None',
 'Bacillus spp, pumilus_None',
 'Bacteroides family_None',
 'Bacteroides fraglis group_None',
 'Basophil Count_10**3/mL',
 'Beta strep, group B, strep. Agalactiae_None',
 'Bicarbonate_mmol/L',
 'Bifidobacerium family_None',
 'Blood Urea Nitrogen (BUN)_mg/dL',
 'Butyrate_mg/mL',
 'CA-19-9 (Pancreatic Cancer)_U/mL',
 'CEA_ng/mL',
 'Calcium_mg/dL',
 'Candida krusei/inconspicua/lambica_None',
 'Candida lusitaniae_None',
 'Candida orthopsilosis_None',
 'Candida parapsilosis_None',
 'Candida pararugosa_None',
 'Candida zeylanoides_None',
 'Cellulosimicrobium cellulans/funkeil/marinum_None',
 'Chloride_mmol/L',
 'Chol/HDL_None',
 'Citrobacter freundii complex_None',
 'Clostridium spp_None',
 'CoQ10_None',
 'Comamonas testosteroni_None',
 'Cortisol Random_None',
 'Corynebacterium falsenii_None',
 'Creatinine_mg/dL',
 'Cryptococcus diffuens_None',
 'Cryptococcus spp, not neoformans_None',
 'DHEA-blood_µg/dL',
 'Direct Bilirubin_None',
 'E. coli spp._None',
 'EOS %',
 'Enterobacter asburiae_None',
 'Enterobacter cloacae_None',
 'Enterococcus spp._None',
 'Esoinophil Count_10**3/mL',
 'Estradiol_pg/mL',
 'Exophiala dermatitidis_None',
 'Fasting Glucose_mg/dL',
 'Ferritin_ng/mL',
 'Fibrinogen_None',
 'Free Testosterone_pg/mL',
 'GGTP_U/L',
 'Gamma Hemolytic Streptococcus_None',
 'Geotrichum spp._None',
 'Globulin_None',
 'HCT_%',
 'HDL (High Density Lipoprotein) "good"_mg/dL',
 'HGB-_g/dL',
 'HOMA-IR (insulin resistance)_None',
 'Hafnia alvei_None',
 'Hemoglobin A1C_%',
 'Hemolytic Escherichia coli_None',
 'High Sensitivity CRP (mg/L)_mg/L',
 'Homocysteine_µmol/L',
 'IDL Chloresterol_None',
 'IgA_None',
 'IgG_None',
 'IgM_None',
 'Insulin_µIU/mL',
 'Iron saturation_%',
 'Iron_µg/dL',
 'Klebsiella oxytoca_None',
 'Klebsiella pneumonia_None',
 'Kocuria spp, salsicia, rhizophila, kristinae_None',
 'LDH_U/L',
 'LYM %',
 'Lactobacillus spp_None',
 'Lactococcus lactis_None',
 'Lp(a) Chloresterol_None',
 'Lp-PLA2_None',
 'Lymphocyte Count_10**3/mL',
 'Lysinibacillus spp_None',
 'MCHC-_g/dL',
 'MCH_pg/cell',
 'MCV-_fL',
 'MONO %',
 'MPV_fL',
 'Magnesium_mg/dL',
 'Monocyte Count_10**3/mL',
 'Morganellla morganii_None',
 'Mucoid Escherichia coli_None',
 'NEU %',
 'Neutrophil Count_10**3/mL',
 'Niacin (Vit B3)_None',
 'PLT-_10**3/mL',
 'PSA Screen_None',
 'Pantoea spp_None',
 'Phosporus_mg/dL',
 'Potassium_mmol/L',
 'Providencia rettgeri_None',
 'Providencia stuartii_None',
 'Pseudomonas aeruginosa_None',
 'Pseudomonas chlororaphis group_None',
 'Pseudomonas citronellolis_None',
 'Pseudomonas stutzeri_None',
 'RBC-_10**6/mL',
 'RDW_%',
 'Ratio APO B100/AI_None',
 'Real-LDL Size Pattern_None',
 'Rhodotorula glutinis/mucilaginosa_None',
 'Rothia dentocariosa/mucliaginosa_None',
 'Saccharomyces cerevisiae/boulardi_None',
 'Selenium_None',
 'Serratia marcescens_None',
 'Sex Hormone Binding Globulin (SHBG)_nmol/L',
 'Sodium_mmol/L',
 'Staphylococcus aureus_None',
 'Staphylococcus epidermidis_None',
 'Staphylococcus haemolyticus_None',
 'Staphylococcus lugdunensis_None',
 'Stool Calprotectin UCSD_µg/g',
 'Stool Calprotectin YFH_None',
 'Stool Lactoferrin_None',
 'Stool Lysozyme_None',
 'Stool SIgA_None',
 'Streptococcus anginosus_None',
 'Streptococcus australis_None',
 'Streptococcus mitis/oralis/cristatus_None',
 'Streptococcus mutans_None',
 'Streptococcus parasanguinis_None',
 'Streptococcus salivarius_None',
 'Streptomyces_None',
 'Sum Total Cholesterol_mg/dL',
 'TG/HDL_None',
 'TIBC_µg/dL',
 'TSH_µIU/mL',
 'Testosterone % Free',
 'Thyroxine (T4)_µg/dL',
 'Tot CO2_None',
 'Total Bilirubin_mg/dL',
 'Total Protein_g/dL',
 'Total SCFA_mg/mL',
 'Total T3_ng/mL',
 'Total Testosterone_ng/mL',
 'Trichosporon asahii_None',
 'Trichosporon montevideense_None',
 'Trichosporon ovoides_None',
 'Triglycerides_mg/dL',
 'UCSD HDL Particle #_μmol/L',
 'UCSD HDL Particle Size_nm',
 'UCSD LDL Particle # by NMR_nmol/L',
 'UCSD LDL Particle Size_nm',
 'UCSD Large HDL Particle #_μmol/L',
 'UCSD Large VLDL Particle #_nmol/L',
 'UCSD Small LDL Particle #_nmol/L',
 'UCSD VLDL Particle Size_nm',
 'UIBC_µg/dL',
 'Uric Acid_None',
 'VLDL Cholesterol_mg/dL',
 'Vitamin B12_pg/mL',
 'Vitamin D, 25-Hydroxy_ng/mL',
 'Vitamin E Alpha-Tocopherol_mg/L',
 'Vitamin E Gamma-Tocopherol_mg/L',
 'WBC-_10**3/mL',
 'Weight_lbs',
 'Zinc_µg/dL',
 'pH_None']

In [15]:
df.rename(columns={
    'HOMA-IR (insulin resistance)_None': 'HOMA_IR',
    'High Sensitivity CRP (mg/L)_mg/L': 'hsCRP',
    'Lp-PLA2_None': 'Lp_PLA2',
    'Fasting Glucose_mg/dL': 'fasting_glucose'
}, inplace=True)

data = df[['Date', 'hsCRP', 'Lp_PLA2', 'fasting_glucose']]
data

           Date  hsCRP  Lp_PLA2  fasting_glucose
0    1993-05-01    NaN      NaN              NaN
1    1996-11-27    NaN      NaN            100.0
2    1997-05-08    NaN      NaN              NaN
3    1998-04-15    NaN      NaN              NaN
4    1999-04-01    NaN      NaN              NaN
..          ...    ...      ...              ...
327  2025-02-05    NaN      NaN             85.0
328  2025-02-12    0.7      NaN            101.0
329  2025-02-28    NaN      NaN              NaN
330  2025-05-20    1.1      NaN            115.0
331  2025-06-13    0.5      NaN             94.0

[332 rows x 4 columns]

In [16]:
print(data.isna().sum())

# only keep rows without NA values in the three columns of interest
data_clean = data.dropna(subset=['fasting_glucose', 'hsCRP', 'Lp_PLA2'], how='any')
data_clean.isna().sum()

print('original data.shape:', data.shape)
print('cleaned data.shape:', data_clean.shape)

Date                 0
hsCRP              165
Lp_PLA2            319
fasting_glucose    167
dtype: int64
original data.shape: (332, 4)
cleaned data.shape: (10, 4)

In [17]:
data_clean

           Date  hsCRP  Lp_PLA2  fasting_glucose
13   2007-11-02    6.1    232.0             98.0
18   2008-08-28   11.3    207.0             89.0
30   2010-03-23    6.7    196.0            109.0
52   2012-05-08    3.2    180.0            103.0
63   2013-07-18    8.3    182.0             96.0
67   2013-11-14    5.0    202.0             96.0
70   2014-03-26    2.4    202.0            100.0
74   2014-07-28    3.7    183.0            107.0
90   2015-04-15    6.5    226.0             97.0
114  2016-02-11    3.4    231.0            101.0

In [30]:
data_long = pd.read_csv("Data/LLM_Biomarkers_Long.csv")
data_long.head()

data_long['Panel'].value_counts()

# filter for Inflammation Panel and Glucose/Insulin Panel 
data_filtered = data_long[data_long['Panel'].isin(['Inflammation Panel', 'Glucose/Insulin Panel'])]
data_filtered.head()

value_num = (data_filtered['Value']
             .astype(str)
             .str.replace(',', '.', regex=False)        # convert 0,5 → 0.5
             .str.extract(r'([-+]?\d*\.?\d+)')[0])      # pull out the numeric token
data_filtered['Value_numeric'] = pd.to_numeric(value_num, errors='coerce')

data_pivot = (
    data_filtered
    .pivot_table(index='Date',
                 columns='Biomarker',
                 values='Value_numeric',
                 aggfunc='mean')
    .reset_index()
)
# pivot the data such that each row is a date and each column is a biomarker
# data_pivot = data_filtered.pivot_table(index='Date', columns='Biomarker', values='Value')
# data_pivot.reset_index(inplace=True)
# data_pivot.head()

data_pivot.head()

/var/folders/81/p6xn6w9d2f36xxx5y2m6yym80000gn/T/ipykernel_19210/3419006841.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered['Value_numeric'] = pd.to_numeric(value_num, errors='coerce')

Biomarker,Date,Fasting Glucose,HOMA-IR (insulin resistance),Hemoglobin A1C,High Sensitivity CRP (mg/L),IgA,IgG,IgM,Insulin,Lp-PLA2
0,1996-11-27,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1999-10-06,79.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2001-05-07,101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2005-10-04,79.0,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN
4,2007-04-17,83.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN